### PR TITLE
[Feature] add CoxPH model

### PR DESCRIPTION
**Pull request by chenpnn**

### CODE REVIEW

**Comment by Mamba413** [comment]
@chenpnn ，by the way, does it multivariate failure time model or just simple cox model?

**Comment by chenpnn** [comment]
> @chenpnn ，by the way, does it multivariate failure time model or just simple cox model?

It is just a simple cox model with scikit-survival type method and data-type.

**Comment by chenpnn** [comment]
> @chenpnn Please do not import `scikit-survival`. In my opinion, it is hard to install this library via github action.

Shall we rewrite the corresponding functions which we imported from scikit-survival?

**Comment by Mamba413** [comment]
@chenpnn  1. Implementing the Cox model has no gain because it is already implemented in `abess`. 2. Maybe you can directly use their implementation. BTW, does `scikit-survival` support the multivariate failure time model?

**Pull request closed without merging**
